# Generated by Django 3.1 on 2020-08-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0003_auto_20200828_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, db_column='username', max_length=240),
        ),
    ]
