# Generated by Django 3.1 on 2020-08-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0006_auto_20200828_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=280)),
                ('suid', models.CharField(max_length=280)),
                ('login', models.CharField(max_length=280)),
                ('sum', models.CharField(max_length=280)),
                ('credit', models.CharField(max_length=280)),
                ('method', models.CharField(max_length=280)),
                ('currency', models.CharField(max_length=280)),
                ('wallet_num', models.CharField(max_length=280)),
                ('wallet_type', models.CharField(max_length=16)),
                ('date_creation', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('batch', models.CharField(max_length=280)),
                ('status', models.CharField(max_length=16)),
            ],
        ),
    ]
