# Generated by Django 3.1 on 2020-08-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0007_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=280)),
                ('rate', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
            ],
        ),
    ]
