# Generated by Django 3.1 on 2020-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0008_finance_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_rates',
            name='date_update',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='finance_rates',
            name='rate',
            field=models.CharField(max_length=280),
        ),
    ]
