# Generated by Django 3.1 on 2020-08-29 19:41

from django.db import migrations
import nx.models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0009_auto_20200828_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroProxyUsers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nx.users',),
            managers=[
                ('objects', nx.models.UserManager()),
            ],
        ),
    ]
