# Generated by Django 3.1 on 2020-08-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0010_heroproxyusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroProxyUsers',
        ),
    ]
