# Generated by Django 3.1 on 2020-09-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0012_counterdisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True),
        ),
    ]
