# Generated by Django 3.1 on 2020-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0013_auto_20200901_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Включено'), (2, 'Выключено')], null=True),
        ),
    ]
