# Generated by Django 3.1 on 2020-09-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0014_auto_20200901_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='display',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Показаты'), (2, 'Скрыть')], null=True),
        ),
    ]
