# Generated by Django 3.1 on 2020-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0015_auto_20200901_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='wallet_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Fiat'), (2, 'Crypto')], null=True),
        ),
    ]
