# Generated by Django 3.1 on 2020-09-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0020_auto_20200901_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='alias',
            field=models.SlugField(),
        ),
    ]
