# Generated by Django 3.1 on 2020-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0021_auto_20200901_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Покупка'), (2, 'Пополниние')], null=True),
        ),
    ]
