# Generated by Django 3.1 on 2020-09-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0022_auto_20200901_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='date_creation',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='requests',
            name='date_update',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_creation',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_update',
            field=models.CharField(max_length=280),
        ),
    ]
