# Generated by Django 3.1 on 2020-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0024_auto_20200903_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=280)),
                ('alias', models.SlugField()),
                ('balance', models.CharField(max_length=280)),
                ('limit_refill', models.CharField(max_length=280)),
                ('limit_buy', models.CharField(max_length=280)),
                ('limit_sell', models.CharField(max_length=280)),
                ('date_update', models.CharField(max_length=280)),
            ],
        ),
    ]
