# Generated by Django 3.1 on 2020-09-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0025_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterDisplay',
        ),
    ]
